server:
  port: 8610


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.130:3306/eboot?serverTimezone=Asia/Shanghai&serverTimezone=Asia/Shanghai&auth-server?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  redis:
    host: 192.168.10.130
    port: 6379
    database: 0
