server:
  port: ${random.int[8000,19000]}


spring:
  datasource:
    dynamic:
      datasource:
        auth:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.10.130:3306/auth?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
          username: root
          password: root
        eboot_sys:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.10.130:3306/eboot_sys?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
          username: root
          password: root
  redis:
    host: 192.168.10.130
    port: 6379
    database: 0
  devtools:
    restart:
      trigger-file: trigger.txt

swagger:
  enable: true
