server:
  port: 8510


spring:
  datasource:
    auth:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.10.130:3306/auth?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root
    eboot_sys:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.10.130:3306/eboot_sys?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root
  redis:
    host: 192.168.10.130
    port: 6379
    database: 0

swagger:
  enable: true
