spring:
  profiles:
    active: dev
  datasource:
    name: mysql1
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    jedis:
      pool:
        max-active: 100
        max-wait: 10
        max-idle: 10
        min-idle: 10

#security:
#  oauth2:
#    resource:
#      jwt:
#        key-uri: ${AUTHORIZATION-SERVER:http://localhost:8000/authorization-server}/oauth/token_key
#    authorization:
#      check-token-access: ${AUTHORIZATION-SERVER:http://localhost:8000/authorization-server}/oauth/check_token


mybatis:
  # 映射文件位置
  mapper-locations: classpath*:mybatis/mapper/*.xml
  #config-location:  classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.glacier.authorization.resource.entity.pojo
  configuration:
    lazy-loading-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    aggressive-lazy-loading: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


## 自定义属性
settings:
  security:
    permit-all:
      - /login
      - /logout
      - /favicon.ico
      - /static/**
      - /webjars/**
      - /actuator/**
      - /druid/**
      - /swagger-ui.html
      - /swagger-resources/**
      - /v2/api-docs
