spring:
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      # 跨域
      globalcors:
        cors-configurations:
          '[/**]':
            # 允许携带认证信息
            allow-credentials: true
            # 允许跨域的源(网站域名/ip)，设置*为全部
            allowed-origins: "*"
            # 允许跨域请求里的head字段，设置*为全部
            allowed-headers: "*"
            # 允许跨域的method， 默认为GET和OPTIONS，设置*为全部
            allowed-methods: "*"
            # 跨域允许的有效期
            max-age: 3600

management:
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
