debug: true

server:
  port: ${random.int[8001,19000]}

## datasource
spring:
  datasource:
    dynamic:
      #设置默认的数据源或者数据源组,默认值即为gen
      primary: gen
      datasource:
        gen:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.10.130:3306/eboot_gen?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
          username: eboot_gen
          password: eboot_gen
#        oracle:
#          driver-class-name: oracle.jdbc.driver.OracleDriver
#          url: jdbc:oracle:thin:@192.168.10.128:1521:XE?characterEncoding=utf8&useSSL=false
#          username: gaedu
#          password: gaedu
#          druid: # 以下是独立参数，每个库可以重新设置
#            validation-query: select 1 FROM DUAL #比如oracle就需要重新设置这个